# Question 1

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

In [2]:
#start=2,stop=50,step size=3
arr = np.arange(2,51,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Question 2

Accept two lists of 5 elements each from the user.

Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [4]:
import numpy as np
#Creating lists

lst1=[]
n= int(input())

for i in range(5):
    num=int(input())
    lst1.append(num)
print("list 1 ", lst1)
    
    #Creating user input list 1
lst2 = []

for i in range(5):
    item =int(input())
    lst2.append(item)
    
print("list 2",lst2)

#converting lists to numpy array
arr1 = np.array((lst1))
arr2 = np.array((lst2))  
print("converted lst1:", arr1)
print()
print("converted lst2:",arr2)
#concatenating  the arrays joins them together
arr3 = np.concatenate((arr1,arr2))
print("Concatenated array :", arr3)

#Sorting the array
arr4=np.sort(arr3)
print("Sorted array :", arr4)

2
3
6
8
1
5
list 1  [3, 6, 8, 1, 5]
5
7
6
9
2
list 2 [5, 7, 6, 9, 2]
converted lst1: [3 6 8 1 5]

converted lst2: [5 7 6 9 2]
Concatenated array : [3 6 8 1 5 5 7 6 9 2]
Sorted array : [1 2 3 5 5 6 6 7 8 9]


### Question 3

Write a code snippet to find the dimensions of a ndarray and its size.

In [12]:
my_array=np.array([[3,4,5], [2,5,6], [6,8,9]])

#printing array dimension
print("Dimension of ndarray:", my_array.ndim)

#printing size(total number of elements ) in an array
print("size of array:",my_array.size)


Dimension of ndarray: 2
size of array: 9


# Question 4

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

Hint: np.newaxis, np.expand_dims

In [25]:
import numpy as np
y= np.array([5,6,7,8,4,5,7])
print (y)
#getting the shape of the array
print( "shape of 1D array:", y.shape)
#Converting 1d array to 2d array
x= y[np.newaxis, :]
print(x)
print( "shape 2D array_row:", x.shape)

#np.expand_dims adds an axis at index position

s=np.expand_dims(y,axis=1)
print("shape 2D array_columns:", s.shape)

[5 6 7 8 4 5 7]
shape of 1D array: (7,)
[[5 6 7 8 4 5 7]]
shape 2D array_row: (1, 7)
shape 2D array_columns: (7, 1)


# Question 5

Consider two square numpy arrays. Stack them vertically and horizontally

Hint.: Use vstack(), hstack

In [35]:
from numpy import vstack
from numpy import hstack #Horizontal stacking is a method merging the arrays horizontally
from numpy import vstack# vertical stacking is merging the array vertically

# vstack
x=np.square([2,3,4])
y=np.square([5,7,8])
a=np.vstack((x,y))
print(a)
print()

#hstack
b=np.hstack((x,y))
print("hstack:",b)

[[ 4  9 16]
 [25 49 64]]

hstack: [ 4  9 16 25 49 64]


# Question 6

How to get unique items and counts of unique items?

In [16]:
#To get the unique values and count we use numpy.unique, return_counts as false or True

a=np.array([2,2,5,6,7,7,8,1])
(unique,counts)=np.unique(a,return_counts=True)
frequencies = np.array((unique,counts)).T
print(frequencies)

[[1 1]
 [2 2]
 [5 1]
 [6 1]
 [7 2]
 [8 1]]
